 server {
	listen 80;

	server_name vespucci.mp;
 
	return 301 https://$host$request_uri;
}

server {
	
    listen 443 ssl;
    server_name vespucci.mp;

	ssl_certificate /etc/letsencrypt/live/vespucci.mp/fullchain.pem;
	ssl_certificate_key /etc/letsencrypt/live/vespucci.mp/privkey.pem;
 
	location / {
		root /usr/share/nginx/html;
		try_files $uri /index.html;
    }
}