version: "3"

services:
  ragemp:
    container_name: ragemp
    build:
      context: .
      dockerfile: Dockerfile
    image: ragemp:latest
    restart: always
    ports:
      - 22005:22005/udp
      - 22006:22006
      - 22007:22007 # Socket.io (Defined in .env)
    networks:
      - my-proxy-net # Reason why: Socket.io must be served over HTTPS.
    volumes:
      - /home/apps/ragemp/game_resources:/server/release/client_packages/game_resources:ro
networks:
  my-proxy-net:
    name: proxynet
    external: true
