import { type LanguagePack } from '@vmp/i18n';

const Language: LanguagePack = {
	description: {
		EN: 'This improves the security of your account and is mandatory for staff members.',
		RO: 'Acest lucru îmbunătățește securitatea contului dvs. și este obligatoriu pentru membrii din staff.'
	},

	'question:1': {
		EN: 'What is two-factor authentication ?',
		RO: 'Ce este two-factor authentication ?'
	},
	'answer:1': {
		EN: 'Two-factor authentication (2FA) is an additional layer of security that requires you to provide two different types of verification before granting access to your account, usually a password and a unique code sent to your phone or email',
		RO: ' Autentificarea în doi pași (2FA) este un nivel suplimentar de securitate pentru conturile tale online, care te ajută să-ți protejezi informațiile sensibile. Funcționează prin cererea a două tipuri diferite de verificare înainte de a acorda acces la contul tău. De obicei, acest lucru implică introducerea unei parole și apoi furnizarea unui cod unic care este trimis pe telefonul tău sau prin email. În acest fel, chiar dacă cineva reușește să obțină parola ta, nu vor putea accesa contul tău fără a avea acces și la telefonul sau emailul tău.'
	},

	'question:2': {
		EN: 'How does it work ?',
		RO: 'Cum functioneaza ?'
	},
	'answer:2': {
		EN: `Two-factor authentication works by requiring you to provide two forms of verification: your password and  a unique code generated by an authenticator app. After you enter your password, the app generates a code that you enter to confirm your identity. This code changes every few seconds, making it difficult for anyone to gain access to your account without your knowledge. You'll need to download an authenticator app, like Google Authenticator or Microsoft Authenticator, to generate the codes.`,
		RO: 'Two-factor authentication funcționează prin cererea a două forme de verificare:  parola și un cod unic generat de o aplicație de autentificare). După ce introduci parola, aplicația generează un cod pe care îl introduci pentru a-ți confirma identitatea. Acest cod se schimbă la fiecare câteva secunde, făcându-l dificil pentru oricine să obțină acces la contul tău fără știrea ta. Va trebui să descarci o aplicație de autentificare, precum Google Authenticator sau Microsoft Authenticator, pentru a genera codurile.'
	},

	button: {
		EN: 'Enable this feature (soon)',
		RO: 'Activați această funcție (în curând)'
	}
};

export default Language;
