import { reasonData } from '@server/definitions/deathReasons';

mp.events.add('loadPlayerDefaults', (player) => {
	player.updateVars({
		isDead: false
	});
});

mp.events.add('playerDeath', (player, reason, killer) => {
	if (!player.vars) return false;
	if (!player.vars.loggedIn) return false;

	mp.events.call(`playerLoggedInDeath`, player, reason, killer);

	return true;
});

mp.events.add('playerLoggedInDeath', (player, reason, killer) => {
	if (player.vars.isDead === true) return false; // Fixing event spam generated by vehicle explosions while doing animations

	player.updateVars({ isDead: true, lastRecoverablePosition: player.position, freshlyWounded: true });

	const fullReason = reasonData[reason];

	player.triggerClientEvent(`showDeathEffect`);

	player.createAmplitudeEvent(`Died`, { fullReason, killer: killer && killer.info ? killer.info.username : `N/A`, isInSafezone: player.vars.isInSafezone });

	player.removeAllWeapons();

	setTimeout(() => {
		const validPlayer = mp.players.at(player.id);
		if (!validPlayer) return; // The player is now offline. Without this check the server may crash.
		mp.events.call('onPlayerSpawn', validPlayer);
		validPlayer.triggerClientEvent('setGodmode', { toggle: true });
		validPlayer.triggerClientEvent('setUnableToDoDamage', { toggle: true });
	}, 3000);

	// Bugfix: It seems Rage:MP when dying by explosions (while doing an animation as passsenger in car) on 02.07.2022 is spamming player death

	setTimeout(() => {
		const validPlayer = mp.players.at(player.id);
		if (!validPlayer) return; // The player is now offline. Without this check the server may crash.
		validPlayer.updateVars({
			isDead: false
		});
		validPlayer.triggerClientEvent('setGodmode', { toggle: false });
		if (!validPlayer.vars.isInSafezone) {
			validPlayer.triggerClientEvent('setUnableToDoDamage', { toggle: false });
		}
	}, 10000);

	return true;
});

declare global {
	interface PlayerVariables {
		freshlyWounded: boolean;
		isDead: boolean;
	}
}

export {};
