const colors: Array<NormalVehiclecolor> = [
	// Metallic
	{ id: 0, label: 'Metallic Black ', hex: '#0d1116 ', type: 'metallic' },
	{ id: 1, label: 'Metallic Graphite Black ', hex: '#1c1d21 ', type: 'metallic' },
	{ id: 2, label: 'Metallic Black Steal ', hex: '#32383d ', type: 'metallic' },
	{ id: 3, label: 'Metallic Dark Silver ', hex: '#454b4f ', type: 'metallic' },
	{ id: 4, label: 'Metallic Silver ', hex: '#999da0 ', type: 'metallic' },
	{ id: 5, label: 'Metallic Blue Silver ', hex: '#c2c4c6 ', type: 'metallic' },
	{ id: 6, label: 'Metallic Steel Gray ', hex: '#979a97 ', type: 'metallic' },
	{ id: 7, label: 'Metallic Shadow Silver ', hex: '#637380 ', type: 'metallic' },
	{ id: 8, label: 'Metallic Stone Silver ', hex: '#63625c ', type: 'metallic' },
	{ id: 9, label: 'Metallic Midnight Silver ', hex: '#3c3f47 ', type: 'metallic' },
	{ id: 10, label: 'Metallic Gun Metal ', hex: '#444e54 ', type: 'metallic' },
	{ id: 11, label: 'Metallic Anthracite Grey ', hex: '#1d2129 ', type: 'metallic' },
	{ id: 15, label: 'Util Black ', hex: '#151921 ', type: 'metallic' },
	{ id: 16, label: 'Util Black Poly ', hex: '#1e2429 ', type: 'metallic' },
	{ id: 17, label: 'Util Dark silver ', hex: '#333a3c ', type: 'metallic' },
	{ id: 18, label: 'Util Silver ', hex: '#8c9095 ', type: 'metallic' },
	{ id: 19, label: 'Util Gun Metal ', hex: '#39434d ', type: 'metallic' },
	{ id: 20, label: 'Util Shadow Silver ', hex: '#506272 ', type: 'metallic' },
	{ id: 27, label: 'Metallic Red ', hex: '#c00e1a ', type: 'metallic' },
	{ id: 28, label: 'Metallic Torino Red ', hex: '#da1918 ', type: 'metallic' },
	{ id: 29, label: 'Metallic Formula Red ', hex: '#b6111b ', type: 'metallic' },
	{ id: 30, label: 'Metallic Blaze Red ', hex: '#a51e23 ', type: 'metallic' },
	{ id: 31, label: 'Metallic Graceful Red ', hex: '#7b1a22 ', type: 'metallic' },
	{ id: 32, label: 'Metallic Garnet Red ', hex: '#8e1b1f ', type: 'metallic' },
	{ id: 33, label: 'Metallic Desert Red ', hex: '#6f1818 ', type: 'metallic' },
	{ id: 34, label: 'Metallic Cabernet Red ', hex: '#49111d ', type: 'metallic' },
	{ id: 35, label: 'Metallic Candy Red ', hex: '#b60f25 ', type: 'metallic' },
	{ id: 36, label: 'Metallic Sunrise Orange ', hex: '#d44a17 ', type: 'metallic' },
	{ id: 38, label: 'Metallic Orange ', hex: '#f78616 ', type: 'metallic' },
	{ id: 43, label: 'Util Red ', hex: '#9c1016 ', type: 'metallic' },
	{ id: 44, label: 'Util Bright Red ', hex: '#de0f18 ', type: 'metallic' },
	{ id: 45, label: 'Util Garnet Red ', hex: '#8f1e17 ', type: 'metallic' },
	{ id: 49, label: 'Metallic Dark Green ', hex: '#132428 ', type: 'metallic' },
	{ id: 50, label: 'Metallic Racing Green ', hex: '#122e2b ', type: 'metallic' },
	{ id: 51, label: 'Metallic Sea Green ', hex: '#12383c ', type: 'metallic' },
	{ id: 52, label: 'Metallic Olive Green ', hex: '#31423f ', type: 'metallic' },
	{ id: 53, label: 'Metallic Green ', hex: '#155c2d ', type: 'metallic' },
	{ id: 54, label: 'Metallic Gasoline Blue Green ', hex: '#1b6770 ', type: 'metallic' },
	{ id: 56, label: 'Util Dark Green ', hex: '#22383e ', type: 'metallic' },
	{ id: 57, label: 'Util Green ', hex: '#1d5a3f ', type: 'metallic' },
	{ id: 61, label: 'Metallic Midnight Blue ', hex: '#222e46 ', type: 'metallic' },
	{ id: 62, label: 'Metallic Dark Blue ', hex: '#233155 ', type: 'metallic' },
	{ id: 63, label: 'Metallic Saxony Blue ', hex: '#304c7e ', type: 'metallic' },
	{ id: 64, label: 'Metallic Blue ', hex: '#47578f ', type: 'metallic' },
	{ id: 65, label: 'Metallic Mariner Blue ', hex: '#637ba7 ', type: 'metallic' },
	{ id: 66, label: 'Metallic Harbor Blue ', hex: '#394762 ', type: 'metallic' },
	{ id: 67, label: 'Metallic Diamond Blue ', hex: '#d6e7f1 ', type: 'metallic' },
	{ id: 68, label: 'Metallic Surf Blue ', hex: '#76afbe ', type: 'metallic' },
	{ id: 69, label: 'Metallic Nautical Blue ', hex: '#345e72 ', type: 'metallic' },
	{ id: 70, label: 'Metallic Bright Blue ', hex: '#0b9cf1 ', type: 'metallic' },
	{ id: 71, label: 'Metallic Purple Blue ', hex: '#2f2d52 ', type: 'metallic' },
	{ id: 72, label: 'Metallic Spinnaker Blue ', hex: '#282c4d ', type: 'metallic' },
	{ id: 73, label: 'Metallic Ultra Blue ', hex: '#2354a1 ', type: 'metallic' },
	{ id: 74, label: 'Metallic Bright Blue ', hex: '#6ea3c6 ', type: 'metallic' },
	{ id: 75, label: 'Util Dark Blue ', hex: '#112552 ', type: 'metallic' },
	{ id: 76, label: 'Util Midnight Blue ', hex: '#1b203e ', type: 'metallic' },
	{ id: 77, label: 'Util Blue ', hex: '#275190 ', type: 'metallic' },
	{ id: 78, label: 'Util Sea Foam Blue ', hex: '#608592 ', type: 'metallic' },
	{ id: 79, label: 'Util Lightning blue ', hex: '#2446a8 ', type: 'metallic' },
	{ id: 80, label: 'Util Maui Blue Poly ', hex: '#4271e1 ', type: 'metallic' },
	{ id: 81, label: 'Util Bright Blue ', hex: '#3b39e0 ', type: 'metallic' },
	{ id: 88, label: 'Metallic Taxi Yellow ', hex: '#ffcf20 ', type: 'metallic' },
	{ id: 89, label: 'Metallic Race Yellow ', hex: '#fbe212 ', type: 'metallic' },
	{ id: 90, label: 'Metallic Bronze ', hex: '#916532 ', type: 'metallic' },
	{ id: 91, label: 'Metallic Yellow Bird ', hex: '#e0e13d ', type: 'metallic' },
	{ id: 92, label: 'Metallic Lime ', hex: '#98d223 ', type: 'metallic' },
	{ id: 93, label: 'Metallic Champagne ', hex: '#9b8c78 ', type: 'metallic' },
	{ id: 94, label: 'Metallic Pueblo Beige ', hex: '#503218 ', type: 'metallic' },
	{ id: 95, label: 'Metallic Dark Ivory ', hex: '#473f2b ', type: 'metallic' },
	{ id: 96, label: 'Metallic Choco Brown ', hex: '#221b19 ', type: 'metallic' },
	{ id: 98, label: 'Metallic Light Brown ', hex: '#775c3e ', type: 'metallic' },
	{ id: 99, label: 'Metallic Straw Beige ', hex: '#ac9975 ', type: 'metallic' },
	{ id: 100, label: 'Metallic Moss Brown ', hex: '#6c6b4b ', type: 'metallic' },
	{ id: 101, label: 'Metallic Biston Brown ', hex: '#402e2b ', type: 'metallic' },
	{ id: 102, label: 'Metallic Beechwood ', hex: '#a4965f ', type: 'metallic' },
	{ id: 103, label: 'Metallic Dark Beechwood ', hex: '#46231a ', type: 'metallic' },
	{ id: 104, label: 'Metallic Choco Orange ', hex: '#752b19 ', type: 'metallic' },
	{ id: 105, label: 'Metallic Beach Sand ', hex: '#bfae7b ', type: 'metallic' },
	{ id: 106, label: 'Metallic Sun Bleeched Sand ', hex: '#dfd5b2 ', type: 'metallic' },
	{ id: 107, label: 'Metallic Cream ', hex: '#f7edd5 ', type: 'metallic' },
	{ id: 108, label: 'Util Brown ', hex: '#3a2a1b ', type: 'metallic' },
	{ id: 109, label: 'Util Medium Brown ', hex: '#785f33 ', type: 'metallic' },
	{ id: 110, label: 'Util Light Brown ', hex: '#b5a079 ', type: 'metallic' },
	{ id: 111, label: 'Metallic White ', hex: '#fffff6 ', type: 'metallic' },
	{ id: 112, label: 'Metallic Frost White ', hex: '#eaeaea ', type: 'metallic' },
	{ id: 122, label: 'Util Off White ', hex: '#dfddd0 ', type: 'metallic' },
	{ id: 125, label: 'Metallic Securicor Green ', hex: '#83c566 ', type: 'metallic' },
	{ id: 127, label: 'police car blue ', hex: '#4cc3da ', type: 'metallic' },
	{ id: 134, label: 'Pure White ', hex: '#ffffff ', type: 'metallic' },
	{ id: 135, label: 'Hot Pink ', hex: '#f21f99 ', type: 'metallic' },
	{ id: 136, label: 'Salmon pink ', hex: '#fdd6cd ', type: 'metallic' },
	{ id: 137, label: 'Metallic Vermillion Pink ', hex: '#df5891 ', type: 'metallic' },
	{ id: 138, label: 'Orange ', hex: '#f6ae20 ', type: 'metallic' },
	{ id: 139, label: 'Green ', hex: '#b0ee6e ', type: 'metallic' },
	{ id: 140, label: 'Blue ', hex: '#08e9fa ', type: 'metallic' },
	{ id: 141, label: 'Mettalic Black Blue ', hex: '#0a0c17 ', type: 'metallic' },
	{ id: 142, label: 'Metallic Black Purple ', hex: '#0c0d18 ', type: 'metallic' },
	{ id: 143, label: 'Metallic Black Red ', hex: '#0e0d14 ', type: 'metallic' },
	{ id: 144, label: 'hunter green ', hex: '#9f9e8a ', type: 'metallic' },
	{ id: 145, label: 'Metallic Purple ', hex: '#621276 ', type: 'metallic' },
	{ id: 146, label: 'Metaillic V Dark Blue ', hex: '#0b1421 ', type: 'metallic' },
	{ id: 147, label: 'MODSHOP BLACK1 ', hex: '#11141a ', type: 'metallic' },
	{ id: 150, label: 'Metallic Lava Red ', hex: '#bc1917 ', type: 'metallic' },
	{ id: 156, label: 'DEFAULT ALLOY COLOR ', hex: '#81827f ', type: 'metallic' },
	{ id: 157, label: 'Epsilon Blue ', hex: '#afd6e4 ', type: 'metallic' },
	// Matte
	{ id: 12, label: 'Matte Black ', hex: '#13181f ', type: 'matte' },
	{ id: 13, label: 'Matte Gray ', hex: '#26282a ', type: 'matte' },
	{ id: 14, label: 'Matte Light Grey ', hex: '#515554 ', type: 'matte' },
	{ id: 21, label: 'Worn Black ', hex: '#1e232f ', type: 'matte' },
	{ id: 22, label: 'Worn Graphite ', hex: '#363a3f ', type: 'matte' },
	{ id: 23, label: 'Worn Silver Grey ', hex: '#a0a199 ', type: 'matte' },
	{ id: 24, label: 'Worn Silver ', hex: '#d3d3d3 ', type: 'matte' },
	{ id: 25, label: 'Worn Blue Silver ', hex: '#b7bfca ', type: 'matte' },
	{ id: 26, label: 'Worn Shadow Silver ', hex: '#778794 ', type: 'matte' },
	{ id: 39, label: 'Matte Red ', hex: '#cf1f21 ', type: 'matte' },
	{ id: 40, label: 'Matte Dark Red ', hex: '#732021 ', type: 'matte' },
	{ id: 41, label: 'Matte Orange ', hex: '#f27d20 ', type: 'matte' },
	{ id: 42, label: 'Matte Yellow ', hex: '#ffc91f ', type: 'matte' },
	{ id: 46, label: 'Worn Red ', hex: '#a94744 ', type: 'matte' },
	{ id: 48, label: 'Worn Dark Red ', hex: '#371c25 ', type: 'matte' },
	{ id: 55, label: 'Matte Lime Green ', hex: '#66b81f ', type: 'matte' },
	{ id: 58, label: 'Worn Dark Green ', hex: '#2d423f ', type: 'matte' },
	{ id: 59, label: 'Worn Green ', hex: '#45594b ', type: 'matte' },
	{ id: 60, label: 'Worn Sea Wash ', hex: '#65867f ', type: 'matte' },
	{ id: 82, label: 'Matte Dark Blue ', hex: '#1f2852 ', type: 'matte' },
	{ id: 83, label: 'Matte Blue ', hex: '#253aa7 ', type: 'matte' },
	{ id: 84, label: 'Matte Midnight Blue ', hex: '#1c3551 ', type: 'matte' },
	{ id: 85, label: 'Worn Dark blue ', hex: '#4c5f81 ', type: 'matte' },
	{ id: 86, label: 'Worn Blue ', hex: '#58688e ', type: 'matte' },
	{ id: 87, label: 'Worn Light blue ', hex: '#74b5d8 ', type: 'matte' },
	{ id: 113, label: 'Worn Honey Beige ', hex: '#b0ab94 ', type: 'matte' },
	{ id: 114, label: 'Worn Brown ', hex: '#453831 ', type: 'matte' },
	{ id: 115, label: 'Worn Dark Brown ', hex: '#2a282b ', type: 'matte' },
	{ id: 116, label: 'Worn straw beige ', hex: '#726c57 ', type: 'matte' },
	{ id: 117, label: 'Brushed Steel ', hex: '#6a747c ', type: 'matte' },
	{ id: 118, label: 'Brushed Black steel ', hex: '#354158 ', type: 'matte' },
	{ id: 119, label: 'Brushed Aluminium ', hex: '#9ba0a8 ', type: 'matte' },
	{ id: 121, label: 'Worn Off White ', hex: '#eae6de ', type: 'matte' },
	{ id: 123, label: 'Worn Orange ', hex: '#f2ad2e ', type: 'matte' },
	{ id: 124, label: 'Worn Light Orange ', hex: '#f9a458 ', type: 'matte' },
	{ id: 126, label: 'Worn Taxi Yellow ', hex: '#f1cc40 ', type: 'matte' },
	{ id: 128, label: 'Matte Green ', hex: '#4e6443 ', type: 'matte' },
	{ id: 129, label: 'Matte Brown ', hex: '#bcac8f ', type: 'matte' },
	{ id: 130, label: 'Worn Orange ', hex: '#f8b658 ', type: 'matte' },
	{ id: 131, label: 'Matte White ', hex: '#fcf9f1 ', type: 'matte' },
	{ id: 132, label: 'Worn White ', hex: '#fffffb ', type: 'matte' },
	{ id: 133, label: 'Worn Olive Army Green ', hex: '#81844c ', type: 'matte' },
	{ id: 148, label: 'Matte Purple ', hex: '#6b1f7b ', type: 'matte' },
	{ id: 149, label: 'Matte Dark Purple ', hex: '#1e1d22 ', type: 'matte' },
	{ id: 151, label: 'Matte Forest Green ', hex: '#2d362a ', type: 'matte' },
	{ id: 152, label: 'Matte Olive Drab ', hex: '#696748 ', type: 'matte' },
	{ id: 153, label: 'Matte Desert Brown ', hex: '#7a6c55 ', type: 'matte' },
	{ id: 154, label: 'Matte Desert Tan ', hex: '#c3b492 ', type: 'matte' },
	{ id: 155, label: 'Matte Foilage Green ', hex: '#5a6352 ', type: 'matte' },
	// Premium
	{ id: 37, label: 'Metallic Classic Gold ', hex: '#c2944f ', type: 'premium' },
	{ id: 47, label: 'Worn Golden Red ', hex: '#b16c51 ', type: 'premium' },
	{ id: 97, label: 'Metallic Golden Brown ', hex: '#653f23 ', type: 'premium' },
	{ id: 120, label: 'Chrome ', hex: '#5870a1 ', type: 'premium' },
	{ id: 158, label: 'Pure Gold ', hex: '#7a6440 ', type: 'premium' },
	{ id: 159, label: 'Brushed Gold ', hex: '#7f6a48 ', type: 'premium' }
];

type NormalVehiclecolor = {
	id: number;
	label: string;
	hex: string;
	type: 'premium' | 'metallic' | 'matte';
};
export default colors;
