const Response = {
	id: '3f1e019b-13eb-4bf0-8c78-6d8c97dbf50f',
	localInfo: {
		ringtone: {
			type: 'preset',
			value: 'default'
		}
	},
	participants: [
		{
			displayName: '456-123',
			role: 'caller',
			status: 'pending',
			joinedAt: '', // will be automatically generated by client-side (when simulating)
			_isLocalPlayer: false
		},
		{
			displayName: 'Boboasca',
			role: 'participant',
			status: 'active',
			joinedAt: '', // will be automatically generated by client-side (when simulating)
			_isLocalPlayer: true
		}
	]
};

export default Response;
